schema_version = "0.0.2"

id = "AetherBlend"
name = "AetherBlend"
tagline = "AetherBlend: Effortless FFXIV Workflows in Blender"
version = "0.0.22"
type = "add-on"
maintainer = "Shino Mythmaker"
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.5.0"
blender_version_max = "5.1.0"
website = "https://github.com/ShinoMythmaker/Aetherblend"
tags = ["Animation", "Rigging", "Import-Export", "3D-View"]

[permissions]
files = "Import files for most Aetherblends functions"


