schema_version = "0.0.2"

id = "AetherBlend"
name = "AetherBlend"
tagline = "AetherBlend: Effortless FFXIV Workflows in Blender"
version = "0.0.22"
type = "add-on"
maintainer = "Shino Mythmaker"
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.5.0"
blender_version_max = "5.1.0"
website = "https://github.com/ShinoMythmaker/Aetherblend"
tags = ["Animation", "Rigging", "Import-Export", "3D-View"]

wheels = [
  "./wheels/requests-2.31.0-py3-none-any.whl",
  "./wheels/urllib3-2.2.1-py3-none-any.whl",
  "./wheels/certifi-2024.2.2-py3-none-any.whl",
  "./wheels/charset_normalizer-3.3.2-py3-none-any.whl",
  "./wheels/idna-3.7-py3-none-any.whl",
]

[permissions]
files = "Import files for most Aetherblends functions"
network = "Connect to FFXIV HTTP server for pose streaming"


